# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ac780e6d100470e3fafeadaa47c693dd89a48c196fd0145c7eb75d8d8362a3010be5bdb815129615206b7f1f8e6e7cf6fe84724ab4ceb6394bab0d9b03725d3b

test:
  secret_key_base: 4ff77703641b0c054243ed382a561ce117bb69ecd8816b414344592f9abbc150f9e9d1c9af8476e5ed10e3ea9ce0f69efcdcc33e647d8ef35ce462651f663b14

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
